#!/bin/sh

doas qemu-system-arm \
	-M virt \
	-cpu cortex-a15 \
	-m 64 \
	-kernel boot.elf \
	-device virtio-blk-device,drive=hd \
	-drive if=none,file=../vexpress-a9/disk.iso,format=raw,id=hd \
	-device virtio-gpu-device \
	-netdev type=tap,id=net0 \
	-device virtio-net-device,netdev=net0 \
	-device virtio-keyboard-device \
	-device virtio-mouse-device \
#	-nographic

