#!/bin/sh

doas cp kern.umg /var/ftpd/
#doas cp vexpress.dtb /var/ftpd/

export ETHER=vether0
export BRIDGE=bridge0

doas qemu-system-arm -M vexpress-a9 -nographic \
	-kernel u-boot \
	-net nic -net tap \
	-sd disk.iso

